[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-core/",
    "solmate/=lib/solmate/",
    "forge-std/=lib/forge-std/src/",
    "@storknetwork/stork-evm-sdk/=stork/stork-external/chains/evm/sdks/stork_evm_sdk/",
    "@stork-example/=stork/stork-external/chains/evm/examples/stork/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
