[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@uniswap/v4-core/=lib/v4-core/",
    "forge-std/=lib/forge-std/src/",
    "@storknetwork/stork-evm-sdk/=stork/stork-external/chains/evm/sdks/stork_evm_sdk/",
    "@stork-example/=stork/stork-external/chains/evm/examples/stork/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
